language:
  ruby

rvm:
  - '2.0'
  - '2.3.1'

matrix:
  fast_finish:
    true

# before_install:
#   - sudo apt-get update -qq
#   - sudo apt-get install ruby gcc ruby-dev rake make -y

cache: bundler



before_script:
  - bundle exec rake compile

script:
  - bundle exec rake spec
  - bundle exec gem build numo-narray.gemspec
  - bundle exec gem install numo-narray-0.9.0.3.gem
