language:
  ruby

rvm:
  - '2.0'
  - '2.1.10'
  - '2.2.5'
  - '2.3.0'

matrix:
  fast_finish:
    true

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install ruby gcc ruby-dev rake make -y

script:
  - gem build numo-narray.gemspec
  - gem install numo-narray-0.9.0.1.gem
  - rspec spec
